# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1500fddb886a8942a7949e1f06500cb0fe316a5b47a1f54f8d094e0e369da41e88076efa5c2b4ef0b6d7cb662898c3fd7aed1132249aeb32409452dd645330dc

test:
  secret_key_base: 325ebd107f369ba7887250c58991ca5071e2851067447d6b4e58132cf682594d7cc3d36cb67b119b288f2098fb424f151d3cb62d1df349763341015326b30c50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
